// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1l8HsZe7qrKEiN76ZN8CD7EQFBn8-7Nk',
    appId: '1:1034748075030:web:be09c8d2fe736b2e3c2937',
    messagingSenderId: '1034748075030',
    projectId: 'clip-all',
    authDomain: 'clip-all.firebaseapp.com',
    storageBucket: 'clip-all.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYhmMqKB93P7TBQZzC65-_yB3i58DD1A',
    appId: '1:1034748075030:android:e39eb4e3f742fd0c3c2937',
    messagingSenderId: '1034748075030',
    projectId: 'clip-all',
    storageBucket: 'clip-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSVbQYeMuUo9Oiv20YtAO-YfBnuxLs6g',
    appId: '1:1034748075030:ios:05971de857a9d84c3c2937',
    messagingSenderId: '1034748075030',
    projectId: 'clip-all',
    storageBucket: 'clip-all.appspot.com',
    iosClientId: '1034748075030-hk1jma168renu287hi89t7h0j4bq6mqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.clip-all',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSVbQYeMuUo9Oiv20YtAO-YfBnuxLs6g',
    appId: '1:1034748075030:ios:05971de857a9d84c3c2937',
    messagingSenderId: '1034748075030',
    projectId: 'clip-all',
    storageBucket: 'clip-all.appspot.com',
    iosClientId: '1034748075030-hk1jma168renu287hi89t7h0j4bq6mqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.clip-all',
  );
}
